### ISSUE TITLE
0.1 - Product

### ISSUE THREAD

**Issue by EntitySK** [CS2103JAN2017-F11-B3/main#6]
This is the sample project morphed to be more like your target product. Functionality can be limited to only those that can be refactored from the sample project. e.g. support for adding and deleting floating tasks.

Submission: Push the code to GitHub and git tag as V0.1. Refer to the Schedule page for further submission instructions.

Grading: To consider this milestone as reached, you should have at least add/delete/find support for floating tasks. You should be able to do that by deleting/renaming the given Address Book code, without having to add too much new code.
The most important thing is not to break the code while morphing sample code to your target product.

**Comment by SmartyMJ** [comment]
#11 #12 #13 #14 #15
