### ISSUE TITLE
0.1 - Documentation

### ISSUE THREAD

**Issue by EntitySK** [CS2103JAN2017-F11-B3/main#7]
Update the following pages:

    About Us page:
    This page is used for module admin purposes. Please follow the format closely to avoid penalties. For example, use a recent solo photo with your face clearly visible (similar to those in the 'Teaching Team' page).
    The photo of a team member should be doc/images/githbubid.png e.g. doc/images/damithc.png where githubid is the team member's GitHub ID in lower case. Remove photos of the SE-EDU developers. No need to include a photo of the supervisor.

    Indicate the different roles played and responsibilities held by each team member. You can reassign these roles and responsibilities later in the project, if necessary.

    Roles and responsibilities
    Roles imply aspects you are in charge of and responsible for. E.g., if you are in charge of documentation, you are the person who should allocate who should write which part, ensure the document is in right format, ensure consistency etc.
    Here are some typical roles:
        Team lead: Responsible for overall project coordination.
        Documentationem> (short for ‘in charge of documentation’): Responsible for the quality of various project documents.
        Testing: Ensures the testing of the project is done properly and on time.
        Code quality: Looks after code quality, ensures adherence to coding standards, etc.
        Deliverables and deadlines: Ensure project deliverables are done on time and in the right format.
        Integration: In charge of versioning of the code, maintaining the code repository, integrating various parts of the software to create a whole.
        Scheduling and tracking: In charge of defining, assigning, and tracking project tasks.
        [Tool ABC] expert: e.g. Eclipse expert, Git expert, etc. Helps other team member with matters related to the specific tool.
        In charge of[Component XYZ]: e.g. In charge of Model, GUI, Storage, etc. If you are in charge of a component, you are expected to know that component well, do the initial refactoring of the component (during V0.1 and V0.2) and review changes done to that component in V0.3-V0.5.
        You may define additional roles.
    Please make sure each of the above roles are assigned to one person in the team. It is OK to have a ‘backup’ for each role, but you should still have one person who is unequivocally the main person playing that role.

    README.md page: Update it to match your project. In particular, add a UI mockup of your intended final product.
    Note that the image of the UI should be doc/images/Ui.png so that it can be downloaded by our scripts.
    Also, remember to acknowledge the original source of the code i.e. The sample project created by SE-EDU initiative at https://github.com/se-edu/

Grading: To consider this milestone as reached, you should have all V0.0 deliverables completed and the two documents mentioned above updated.

**Comment by SmartyMJ** [comment]
We need to update the About Us page and make sure it meets all requirements (with accurate roles and responsibilities). @CS2103JAN2017-F11-B3/developers

**Comment by SmartyMJ** [comment]
We also need to update the README.md page with a UI mockup. @SmartyMJ
