### ISSUE TITLE
0.2 - Product

### ISSUE THREAD

**Issue by EntitySK** [CS2103JAN2017-F11-B3/main#8]
This is the first MVP (Minimum Viable Product) version of the product.

    It should be a viable, possibly minimal product. This is not a walking skeleton. A user should be able to use it. It may not be user-friendly, but it should not be unusable. Try to include at least the basic CRUD facilities for at least one type of tasks. Here are some examples that are NOT acceptable:
        example 1. Has a well-developed functionality to add tasks but does not support commands for deleting or editing tasks: This is not usable because the user cannot rectify errors made while creating tasks.
        example 2. Has all the CRUD functionality implemented but they are not connected to the UI: This too is not usable by the end-user.
    While this is an internal release (not a production release), you are expected to maintain a reasonable code quality at all times. In particular, you should comply with the coding standard all the time.

Submission: Push the code to GitHub and git tag as V0.2. In addition, the issues assigned to V0.2 milestones and the milestones itself should be closed on your team's GitHub repo before tutorial.

**Comment by ctleungac** [comment]
1. include CRUD (create, read, update, delete) facilities for at least one type of tasks
2. CRUD connect to UI
